parameters:
#    assoc_landing.example.class: Assoc\Bundle\LandingBundle\Example

services:
#    assoc_landing.example:
#        class: %assoc_landing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
