assoc_landing:
    resource: "@AssocLandingBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
    
#demo_bundle:
#    resource: '@AcmeDemoBundle/Resources/config/routing.yml'
    